#+title: Deposit Betas
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+HTML_HEAD: <style>pre.src{background:#343131;color:white;} </style>
#+PROPERTY: header-args    :exports none

* Deposits

  Banks accept deposits (into savings and checking accounts) and use those deposits to fund loans such as mortgages.  Deposits are a liability for the bank and the bank pays the floating deposit rate.  The loans are assets to the bank, and often they pay a fixed rate.

  Banks generally pay deposit rates which are below market short-term interest rates.  Therefore banks rely on their /deposit franchise/ for inexpensive funding.

* Deposit Beta

The **Beta** of the deposits means the sensitivity of deposit rates to short-term interest rate changes (often the Federal Funds rate).

#+begin_quote
Beta: the change in deposit rates given a change in short-term interest rates.
#+end_quote

** NYU Dataset

Researchers at NYU provide a dataset with the deposit beta for each bank.  We can download this data with:

#+begin_src python
import pandas as pd

def get_beta_data():
    

#+end_src
